application: cmunerf
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /admin/.*
  script: simpleApp.app
  login: admin
- url: /.*
  script: simpleApp.app
  login: required
